---
title: "Littter"
author: "Chen-Chia Ku"
date: "2022-11-23"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 1. Library讀入
```{r message=FALSE, warning=FALSE}
setwd("D:/Drive/2_lab/Ku3.1_LitterfallSin/LitterfallSin")
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(readr)
library(glue)
library(ggtext)
library(forcats)
```

# 2. 資料輸入
```{r message=FALSE, warning=FALSE}
Littdt <- read.csv("D:/Drive/2_lab/Ku3.1_LitterfallSin/Data/Shin2012_2022.csv")
habidt <- read.csv("D:/Drive/2_lab/Ku3.1_LitterfallSin/Data/litHabitat3site.csv")
brandt <- read.csv("D:/Drive/2_lab/Ku3.1_LitterfallSin/Data/Shin2012branch_2022.csv")
speciesList <- read.csv("D:/Drive/2_lab/Ku3.1_LitterfallSin/Data/LitterSpeciesTab.csv")

```

# 3. 資料整理
```{r message=FALSE, warning=FALSE}
## 凋落葉資料
Littdt1 <- Littdt %>%
  mutate(site=ifelse(X1==2|X1==6|X1==10|X1==7|X1==11, "Nan", "Lan")) %>%
  mutate(plot=paste(site, X1, Y1)) %>%
  mutate(portion="leaf") %>%
  dplyr::select(-Quadrat, -WeightHA)
  
## 枝條、殘渣、花果資料
brandt1 <- brandt %>%
  mutate(plot=paste(site, X1, Y1))

## 生育地資料
habidt1 <- habidt %>%
  mutate(plot=paste(qua, X1, Y1)) %>%
  distinct()

## 合併凋落葉、枝條、生育地資料
Littdt2 <- bind_rows(Littdt1, brandt1) %>%
  left_join(habidt1 %>% dplyr::select(plot, habitat) ,
            by=c("plot"="plot"))
```

# 每個月分個個凋落物網，不分物種、不分生育地
```{r}
MonLit0.1 <- Littdt2 %>%
  group_by(Time, plot,  portion) %>%
  summarise(W=sum(Weight)) %>%
  ungroup() %>%
  group_by(Time,portion) %>%
  summarise(Wmean=mean(W), 
            Wsd=sd(W)) %>%
  ungroup() %>%
  mutate(portion=factor(portion, levels= c("leaf", "branch", "flower", "fruit", "other"))) 

PortionPlot <-ggplot(MonLit0.1, mapping=aes(x=Time, y=Wmean))+
  geom_line(aes(group=portion, color=portion))+
  geom_point(aes(color=portion))+
  scale_color_manual(name="portion", 
                      values=c("#386641","#6a994e","#bc4749","#a7c957","#e5d2a1"))+
  labs(title = "overall") +
  theme(panel.border = element_rect(colour = "black", fill=NA, linewidth = 1.5),
        panel.background = element_rect(fill = "white"), 
        legend.position="none")
  

PortionPlot 
```


# 4.每個月份各個凋落物網，不分物種的的凋落物量
```{r message=FALSE, warning=FALSE}
MonLit0 <- Littdt2 %>%
  group_by(Time, plot, habitat, portion) %>%
  summarise(W=sum(Weight)) %>%
  ungroup()%>%
  mutate(portion=factor(portion, levels= c("leaf", "branch", "flower", "fruit", "other")))

MonLit1 <- MonLit0 %>%
  group_by(Time, habitat, portion) %>%
  summarise(Wmean=mean(W)/0.05041,  #kg ->/0.05041, t->/50.41
            Wsd=sd(W)/0.05041) %>%  #kg ->/0.05041, t->/50.41
  ungroup() %>%
  mutate(habitat=ifelse(habitat==0, "windward", 
                        ifelse(habitat==1, "leeward", "creek"))) %>%
  mutate(habitat=factor(habitat, levels= c("windward", "leeward", "creek"))) %>%
  mutate(portion=factor(portion, levels= c("leaf", "branch", "flower", "fruit", "other")))

Habitatportion <- ggplot()+
  geom_col(MonLit1, mapping=aes(x=habitat, y=Wmean, 
                                fill=factor(portion, levels=c("other", "fruit", "flower","branch","leaf" ))),
           position="stack", 
           width=0.8)+
  facet_wrap(~Time, nrow=1) +
  scale_fill_manual(name="portion", 
                      values=c("#A9D18E","#0070C0","#FF0000","#ED7D31","#548235"))+
  ylab(expression("Litterfall (Kg ha"^-1*"mon"^-1*")"))

Habitatportion
ggexport(Habitatportion, filename = file.path("Output","Habitatportion.png"), width=9000, height=5000, res=900 )



```

```{r}


#AllPortionPlot <- ggarrange(PortionPlot,Allplot, nrow=2, heights = c(3,1) )

#ggarrange(AllPortionPlot ,Habitatportion2, ncol=2, common.legend = T, legend = "right", widths = c(2,1) )


```

# 5.各生育地內的差異
```{r message=FALSE, warning=FALSE}
#不分Portion
MonLit2 <- MonLit0 %>%
  group_by(Time, plot, habitat) %>%
  summarise(Wei=sum(W)) %>%
  ungroup()

##各個樣區內不分portion的數值分布
LitterPlot <- ggplot()+
  geom_boxplot(MonLit2, mapping=aes(x=as.factor(habitat), y=Wei, fill=as.factor(habitat)))+
  facet_wrap(~Time, ncol=12)+
  scale_fill_manual(name="habitat", values = c("#f07167", "#fed9b7","#0081a7"))+
  ylab("Weight(kg)")+
  xlab("Habitat")
LitterPlot
ggexport(LitterPlot, filename = file.path("Output","LitterPlot.png"), width=7000, height=5000, res=800 )

#各生育地內各月份的凋落物量
MonLit2.1 <- MonLit2 %>%
  group_by(Time, habitat) %>%
  summarise(wei=mean(Wei)/0.05041, 
            sd=sd(Wei)/0.05041) %>%
  ungroup()

Litterhabitat <- ggplot(MonLit2.1, mapping=aes(x=Time, y=wei))+
  geom_col( aes(fill=as.factor(habitat)), position = "dodge", color="black")+
  geom_errorbar(aes(ymin=wei, ymax=wei+sd, group=as.factor(habitat)), position=position_dodge(), color="black")+
  
  scale_fill_manual(name="habitat",label=c("windward", "leeward", "creek") ,values = c("#f07167", "#fed9b7","#0081a7"))+
  ylab(expression("Weight (kg ha"^-1*")"))
Litterhabitat
ggexport(Litterhabitat , filename = file.path("Output","Litterhabitat .png"), width=7000, height=5000, res=800 )

# 各生育地在一年內的凋落物量
MonLit3 <- MonLit2 %>%
  group_by(Time, habitat) %>%
  summarise(wei=sum(Wei)) %>%
  ungroup()
## 檢視時間的樹直分布
ggplot()+
  geom_boxplot(MonLit3, mapping=aes(x=as.factor(habitat), y=wei, fill=as.factor(habitat)))

MonLit3.1 <- MonLit3 %>%
  group_by(habitat) %>%
  summarise(wei=mean(wei), 
            sd=sd(wei)) %>%
  ungroup()


ggplot()+
  geom_col(MonLit3.1, mapping=aes(x=as.factor(habitat), y=wei))

```

## 不同功能部位，不同生育地
```{r}

MonLit5 <- MonLit0 %>%
  group_by(plot, habitat, portion) %>%
  summarise(wei=sum(W)) %>%
  ungroup()

MonLit5.1 <- MonLit5 %>%
  group_by(habitat, portion) %>%
  summarise(mean=mean(wei, na.rm=T)/50.41, 
            sd=sd(wei, na.rm=T)/50.41) %>%
  ungroup()

ggplot()+
  geom_boxplot(MonLit5.1, mapping=aes(x=as.factor(portion), y=mean, fill=as.factor(portion)))

```

# 6.所有時間總量變化
```{r message=FALSE, warning=FALSE}
MonLit4 <- MonLit0 %>%
  group_by(Time, plot) %>%
  summarise(W=sum(W)) %>%
  ungroup() %>%
  group_by(Time) %>%
  summarise(Wmean=mean(W), 
            sd=sd(W)) %>%
  ungroup()


ggplot()+
  geom_col(MonLit4, mapping=aes(x=Time, y=Wmean))
```


```{r}


Allplot <- ggplot(data=MonLit4, mapping=aes(x=Time, y=Wmean))+
  geom_col(fill="grey40")+
  geom_errorbar(aes(ymax=Wmean+sd, ymin=Wmean), color="grey40", width=0.2)+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1.5),
        panel.background = element_rect(fill = "white"))
Allplot



```

# 7. 直鏈烷濃度
## 
```{r message=FALSE, warning=FALSE}
AKdt3 <- read.csv("D:/Drive/2_lab/Ku3.1_LitterfallSin/Data/AKdt3_ZI.csv")
Akdt3.1 <- AKdt3 %>%
  filter(Delete==0)

SPdt <- Littdt2 %>%
  filter(portion=="leaf")

```

## 7.1物種葉子的直鏈烷濃度
```{r message=FALSE, warning=FALSE}

SPdtx <- SPdt %>%
  left_join(Akdt3.1 %>%dplyr::select(sp, Akcon) , by = c("Species"="sp")) %>%
  mutate(Species2=ifelse(is.na(Akcon), "Leafother", Species)) %>%
  group_by(Time, habitat, Species2) %>%
  summarise(Weight=sum(Weight)) %>%
  ungroup() %>%
  group_by(Time, habitat) %>%
  mutate(Wtotal=sum(Weight)) %>%
  ungroup() %>%
  mutate(percent=(Weight/Wtotal)*100) %>%
  left_join(Akdt3.1 %>%dplyr::select(sp, Akcon) , by = c("Species2"="sp")) %>%
  mutate(Concentration=Akcon*percent/100) %>%
  group_by(Time, habitat) %>%
  mutate(Ctotal=sum(Concentration, na.rm=T)) %>%
  ungroup() %>%
  mutate(Akcon2=ifelse(is.na(Akcon), Ctotal, Akcon)) %>% 
  mutate(flux=Weight*Akcon2)
```


## 7.2枝條、花果、殘渣的直鏈烷濃度
```{r message=FALSE, warning=FALSE}

BFdt <- Littdt2 %>%
  filter(portion!="leaf") %>%
  group_by(Time, habitat, portion) %>%
  summarise(Weight=sum(Weight)) %>%
  ungroup() %>%
  mutate(Akcon2=ifelse(portion=="branch", 140,
                       ifelse(portion=="flower", 284,
                              ifelse(portion=="fruit", 94,
                                     ifelse(portion=="other", 497,"X"))))) %>%
  mutate(Akcon2=as.numeric(Akcon2)) %>%
  mutate(flux=Weight*Akcon2) %>%
  mutate(Species2="-")

```

## 7.3 結合葉、花、果實、枝條與殘渣的資料
```{r message=FALSE, warning=FALSE}
SPdtx1 <- SPdtx %>%
  dplyr::select(Time, habitat, Species2, Weight, Akcon2, flux) %>%
  mutate(portion="leaf")

  
SPBFdt <- bind_rows(SPdtx1, BFdt) 
```


##7.4繪製不同物種、葉、花、果實、枝條與殘渣比例的圓餅圖
```{r message=FALSE, warning=FALSE}
SPBFdt0 <- SPBFdt %>%
  group_by()




SPBFdt1 <- SPBFdt %>%
  group_by(portion, Species2, habitat) %>%
  summarise(Weight=sum(Weight), 
            flux=sum(flux), 
            Akcon2=mean(Akcon2)) %>%
  ungroup() %>%
  group_by(habitat) %>%
  mutate(Percent=flux/sum(flux)*100) %>%
  ungroup() %>%
  arrange(habitat, desc(Percent))

SPBFdt1_leaf <- SPBFdt1  %>%
  filter(portion=="leaf") %>%
  group_by(habitat) %>%
  mutate(threshod=quantile(Percent, 0.84)) %>%
  mutate(Q=ifelse(Percent>threshod, 1,0)) %>%
  mutate(Q=ifelse(grepl('未知', Species2), 0,Q)) %>%
  mutate(Percent2= ifelse(Q==1, Percent, sum(Percent[Q==0]) )) %>%
  ungroup() %>%
  mutate(Species2=ifelse(Q==0, "othersp", Species2)) %>%
  dplyr::select(-threshod, -Q) %>%
  group_by(portion, habitat, Species2) %>%
  summarise(Weight=sum(Weight), 
            flux=sum(flux), 
            Akcon2=mean(Akcon2), 
            Percent2=mean(Percent2))%>%
  ungroup() %>%
  arrange(desc(habitat), (Percent2), desc(Species2))

SPBFdt1.0 <- SPBFdt1  %>%
  filter(portion!="leaf")  %>%
  mutate(Percent2=Percent) %>%
  arrange(desc(habitat), desc(Percent2), Species2)

SPBFdt0.0 <- bind_rows(SPBFdt1.0,SPBFdt1_leaf)


SPBFdt1.1 <- SPBFdt0.0 %>%
  #arrange(desc(habitat), desc(Percent2), desc(portion)) %>%
  #arrange(habitat, portion,Percent, desc(Species2)) %>%
  group_by(habitat) %>%
  mutate(csum = rev(cumsum(rev(Percent2))), 
         pos0=cumsum((Percent2)-(0.5*Percent2)),
         pos1=pos0*2-pos0/8)%>%
  ungroup() %>%
  
  left_join(speciesList %>% dplyr::select(Name, speciesName, Genus, Sp:varName), by=c("Species2"="Name")) %>%
  mutate(speciesName=ifelse(is.na(speciesName), Species2, speciesName)) %>%
  mutate(Gene = glue("<i>{Genus} {Sp}</i> {var} <i>{varName}</i>"))

```

### 繪製圓餅圖
```{r}


WindSPBFdt1.1 <- SPBFdt1.1 %>% 
  filter(habitat==0)


Wportion <- ggplot(SPBFdt1.1 %>% filter(habitat==0),
                   mapping=aes(x=1, Percent2, fill=fct_inorder(portion)))+
  geom_col(color="black", size=0.2, 
           position=position_stack(reverse=T))+
  scale_fill_manual(name="Litter portion", 
                    breaks=c("fruit", "flower", "branch", "leaf","other"),
                   values=c("#38a3a5","#22577a","#c7f9cc", "#57cc99","#80ed99"))+
  geom_text_repel(SPBFdt1.1 %>% filter(habitat==0, portion=="leaf"),
                  mapping=aes(x=1.4, label = fct_inorder(speciesName), y=pos1), 
                  nudge_x = 0.3,nudge_y =-1, 
                  segment.size = .7, 
                  size = 3.3, show.legend = F, color="grey20",
                  fontface = c("italic"))+
  geom_text(SPBFdt1.1 %>% filter(habitat==0, portion=="leaf"),
                  mapping=aes(x=0.8, label = paste(round(Percent2, 2),"%"), y=pos1)) +
                  #size = 3.3, show.legend = F, color="grey30",
                  #fontface = c("italic"))+
  geom_text(mapping=aes(x=-0.5, y=1, 
                        label=paste("Windward habitat", "\n", "Flux:3.09")), 
            color="black", family="sans",fontface="bold", size=5)+
  #geom_text_repel(mapping=aes(x=-0.6, y=1, label="Flux:3.09"), color="black", family="serif")+
  coord_polar(theta = "y", start=0)+
  theme_void()+
  xlim(c(-0.5, 1.8))


Wportion

Lportion <- ggplot(SPBFdt1.1 %>% filter(habitat==1),
                   mapping=aes(x=1, Percent2, fill=fct_inorder(portion)))+
  geom_col(color="black", size=0.2, 
           position=position_stack(reverse=T))+
  scale_fill_manual(name="Litter portion", 
                    breaks=c("fruit", "flower", "branch", "leaf","other"),
                   values=c("#38a3a5","#22577a","#c7f9cc", "#57cc99","#80ed99"))+
  geom_text_repel(SPBFdt1.1 %>% filter(habitat==1, portion=="leaf"),
                  mapping=aes(x=1.4, label = fct_inorder(speciesName), y=pos1), 
                  nudge_x = 0.3,nudge_y =-1, 
                  segment.size = .7, 
                  size = 3.3, show.legend = F, color="grey20",
                  fontface = c("italic"))+
  geom_text(SPBFdt1.1 %>% filter(habitat==1, portion=="leaf"),
                  mapping=aes(x=0.8, label = paste(round(Percent2, 2),"%"), y=pos1)) +
                  #size = 3.3, show.legend = F, color="grey30",
                  #fontface = c("italic"))+
  geom_text(mapping=aes(x=-0.5, y=1, 
                        label=paste("Leeward habitat", "\n", "Flux:3.09")), 
            color="black", family="sans",fontface="bold", size=5)+
  #geom_text_repel(mapping=aes(x=-0.6, y=1, label="Flux:3.09"), color="black", family="serif")+
  coord_polar(theta = "y", start=0)+
  theme_void()+
  xlim(c(-0.5, 1.8))
Lportion

Cportion <-ggplot(SPBFdt1.1 %>% filter(habitat==2),
                   mapping=aes(x=1, Percent2, fill=fct_inorder(portion)))+
  geom_col(color="black", size=0.2, 
           position=position_stack(reverse=T))+
  scale_fill_manual(name="Litter portion", 
                    breaks=c("fruit", "flower", "branch", "leaf","other"),
                   values=c("#38a3a5","#22577a","#c7f9cc", "#57cc99","#80ed99"))+
  geom_text_repel(SPBFdt1.1 %>% filter(habitat==2, portion=="leaf"),
                  mapping=aes(x=1.4, label = fct_inorder(speciesName), y=pos1), 
                  nudge_x = 0.3,nudge_y =-1, 
                  segment.size = .7, 
                  size = 3.3, show.legend = F, color="grey20",
                  fontface = c("italic"))+  
  geom_text(SPBFdt1.1 %>% filter(habitat==2, portion=="leaf"),
                  mapping=aes(x=0.8, label = paste(round(Percent2, 2),"%"), y=pos1)) +
  geom_text(mapping=aes(x=-0.5, y=1, 
                        label=paste("Creek habitat", "\n", "Flux:7.02")), 
            color="black", family="sans",fontface="bold", size=5)+
                  #size = 3.3, show.legend = F, color="grey30",
                  #fontface = c("italic"))+

  #geom_text_repel(mapping=aes(x=-0.6, y=1, label="Flux:3.09"), color="black", family="serif")+
  coord_polar(theta = "y", start=0)+
  theme_void()+
  xlim(c(-0.5, 1.8))
Cportion



ThreeHabitat <- ggarrange(Wportion, Lportion, Cportion, ncol=1, common.legend = T)
ThreeHabitat
ggexport(ThreeHabitat, filename =file.path("Output", "ThreeHabitat.png"), width=6000, height=14000, res=800 )


```

## 7.5 每個物種的排名
放入Figure裡面
```{r}
SPBFdt3 <- SPBFdt1 %>%
  filter(portion=="leaf") %>%
  filter(!grepl('未知', Species2), Species2!="Leafother") %>%
  arrange(desc(habitat), desc(Weight)) %>%
  left_join(speciesList %>% dplyr::select(Name, speciesName, Genus, Sp:varName), by=c("Species2"="Name")) %>%
  mutate(Gene = glue("<i>{Genus} {Sp}</i> {var} <i>{varName}</i>"))

SpeciesW <- ggplot(SPBFdt3)+
  geom_col(mapping=aes(x=fct_inorder(Gene),y= Weight,fill=as.factor(habitat)), 
           position = position_dodge2(width = 2, preserve = "single"))+
  scale_y_sqrt(breaks=c(0,1,10,100,1000), labels=c(0,1,10,100,1000), limits=c(0,1000), expand=c(0,0))+
  scale_fill_manual(name="habitat", values = c("#eb3f31", "#fdb069","#0081a7"))+
  coord_flip()+
  theme(panel.border = element_rect(colour = "black", fill=NA, linewidth=1.5),
        panel.background = element_rect(fill = "white"),
        axis.text.y = ggtext::element_markdown())+
  xlab("Species Name")+
  ylab("Weight (total weight)")

SpeciesW

ggexport(SpeciesW, filename = file.path("Output", "SpeciesW.png"), width=6000, height=7200, res=1000)

```

```{r}
Litt2SPBF <- Littdt2 %>%
  left_join(SPBFdt %>% dplyr::select(-Weight, -flux), 
            by=c("portion"="portion","Species"="Species2", "Time"="Time", "habitat"="habitat")) %>%
  mutate(sp=ifelse(is.na(Akcon2), "Leafother", Species)) %>%
  left_join(SPBFdt %>% dplyr::select(-Weight, -flux), 
            by=c("portion"="portion","sp"="Species2", "Time"="Time", "habitat"="habitat")) %>%
  dplyr::select(-Akcon2.x) %>%
  rename(Akcon2=Akcon2.y) %>%
  mutate(flux=Weight*Akcon2)


MonLitt2SPBF1 <- Litt2SPBF  %>%
  group_by(Time, plot,  portion) %>%
  summarise(W=sum(Weight), 
            Flux=sum(flux)) %>%
  ungroup() %>%
  group_by(Time,portion) %>%
  summarise(Wmean=mean(W)/50.41, 
            Wsd=sd(W)/50.41, 
            Fmean=mean(Flux)/50.41, 
            Fsd=sd(Flux)/50.41) %>%
  ungroup() %>%
  mutate(portion=factor(portion, levels= c("leaf", "branch", "flower", "fruit", "other")))
```


# 8.化合物組成
```{r message=FALSE, warning=FALSE}
#Data
Compodt <-  read.csv("D:/Drive/2_lab/Ku3.1_LitterfallSin/Data/Compodt.csv")

#overall Data
Compodt2 <- Compodt %>%
  left_join(AKdt3 %>% dplyr::select(Species, sp, Delete), by=c("Species"="Species")) %>%
  filter(Delete==0) %>%
  gather("Cvariable", "Cvalue0",C14:C35) %>%
  dplyr::select(-Species, -Delete)

#已檢測的樹種
Compodt3 <- Compodt2 %>%
  left_join(SPdtx, by=c("sp"="Species2")) %>%
  mutate(Cvalue=Cvalue0*percent/100) %>%
  mutate(portion="leaf")

Compodt4 <- Compodt3 %>%
  dplyr::select(-Cvalue0, -Weight:-flux) %>%
  rename(Species="sp")

#未檢測的樹種資料
CompoUN <- Compodt3 %>%
  group_by(Time, habitat, Cvariable) %>%
  summarise(Cvalue=sum(Cvalue, na.rm = T)) %>%
  ungroup() %>% 
  mutate(portion="leaf") %>%
  mutate(Species="leafother")

##樹枝其他化合物組成
BranCompodt <-read.csv("D:/Drive/2_lab/Ku3.1_LitterfallSin/Data/BranchCompo.csv")

BranCompodt1 <- BranCompodt %>%
  gather("Cvariable", "Cvalue",C14:C35) %>%
  mutate(habitat_0=0, 
          habitat_1=1, 
          habitat_2=2)%>%
  gather("variable", "habitat", habitat_0:habitat_2) %>%
  dplyr::select(-variable) %>%
  mutate(Time="All", 
         Species="-")

CompoAll <- bind_rows(Compodt4,CompoUN,BranCompodt1)

```

## 8.1重量與化合物的合併
```{r message=FALSE, warning=FALSE}
SPBFdt2 <- SPBFdt %>%
  mutate(Time=ifelse(portion!="leaf", "All", Time )) %>%
  group_by(Time, habitat, portion) %>%
  summarise(Weight=sum(Weight)) %>%
  ungroup()


CompoAll2 <- CompoAll %>% 
  filter(Species!="leafother") %>%
  group_by(Time, Cvariable, habitat, portion) %>% 
  summarise(Cvalue=sum(Cvalue)) %>%
  ungroup()

SPBCompo <- CompoAll2 %>%
  left_join(SPBFdt2, by=c("Time"="Time", "habitat"="habitat", "portion"="portion")) %>%
  mutate(flux=Cvalue*Weight) %>%
  group_by(portion, habitat, Cvariable) %>%
  summarise(Cvalue=sum(Cvalue), 
            Weight=sum(Weight),
            flux=sum(flux)) %>%
  ungroup() %>%
  group_by(portion, habitat) %>%
  mutate(Relative=flux/sum(flux)*100) %>%
  ungroup() %>%
  mutate(habitat=ifelse(habitat==0, "windward", 
                        ifelse(habitat==1, "leeward", "creek")))
  
```

## 8.2繪製不同化合物組成的通量
```{r message=FALSE, warning=FALSE}
Cvariable <- ggplot()+
  geom_col(SPBCompo, mapping=aes(x=Cvariable, y=flux))+
  facet_wrap(~ factor(habitat, levels=c("windward", "leeward", "creek"))+
               factor(portion, levels=c("leaf", "branch", "flower", "fruit", "other")),ncol=5)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

Cvariable 
ggexport(Cvariable, filename = file.path("Output","Cvariable.png"), width=8000, height=4000, res=600 )

```


```{r}
SPBCompo1 <- SPBCompo %>%
  group_by(habitat, portion, Cvariable) %>%
  summarise(fluxall=sum(flux)) %>%
  ungroup() %>%
  mutate(portion=factor(portion, levels= c("leaf", "branch", "flower", "fruit", "other")))

```

```{r}
Cvariable2 <- ggplot()+
  geom_col(SPBCompo1, mapping=aes(x=Cvariable, y=fluxall, fill=portion), position = "stack")+
  scale_y_continuous(expand = c(0,0), limits = c(0,1500000))+
  scale_fill_manual(name="Litter portion", 
                   values=c("#38a3a5","#22577a","#c7f9cc", "#57cc99","#80ed99"))+
  facet_wrap(~ factor(habitat, levels=c("windward", "leeward", "creek")))+
  
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        panel.border = element_rect(colour = "grey60", fill=NA, size=1),
        panel.background = element_rect(fill = "white"))+
  xlab("Carbon number of n-Alkane")+
  ylab("Flux (ug)")

Cvariable2

ggexport(Cvariable2, filename = file.path("Output","Cvariable2.png"), width=6000, height=4000, res=650 )
```

```{r}
SPBCompo_wide <- SPBCompo1 %>%
  spread(Cvariable, fluxall)

SPBCompo2 <- SPBCompo_wide %>%
  mutate(CPI=(((C25+C27+C29+C31+C33)/(C24+C26+C28+C30+C32))+((C25+C27+C29+C31+C33)/(C26+C28+C30+C32+C34)))*0.5)


CompoAll_wide <- CompoAll %>%
  spread(Cvariable, Cvalue) %>%
  mutate(Species2=ifelse(Species=="-", portion, Species))%>%
  mutate(CPI=(((C25+C27+C29+C31+C33)/(C24+C26+C28+C30+C32))+((C25+C27+C29+C31+C33)/(C26+C28+C30+C32+C34)))*0.5)

```

# play
```{r}
SpeciesW <- ggplot(SPBFdt3)+
  geom_col(mapping=aes(x=fct_inorder(Gene),y= Weight,fill=as.factor(habitat)), 
           position = position_dodge2(width = 2, preserve = "single"))+
  scale_y_sqrt(breaks=c(0,1,10,100,1000), labels=c(0,1,10,100,1000), limits=c(0,1000), expand=c(0,0))+
  scale_fill_manual(name="habitat", values = c("#eb3f31", "#fdb069","#0081a7"))+
  coord_flip()+
  coord_polar(start = 0)+
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,5), "cm",),
    panel.background = element_rect(fill = "white"),
    axis.text.y = ggtext::element_markdown()) 

  theme(panel.border = element_rect(colour = "black", fill=NA, linewidth=1.5),
        panel.background = element_rect(fill = "white"),
        axis.text.y = ggtext::element_markdown())+
  xlab("Species Name")+
  ylab("Weight (total weight)")

SpeciesW
```



